
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 22 08:57:14 CEST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AT = 46;
  public static final int AS = 6;
  public static final int FROM = 18;
  public static final int B_XOR = 51;
  public static final int GT = 54;
  public static final int ARROW = 70;
  public static final int PLUS_EQ = 71;
  public static final int NEWLINE = 86;
  public static final int RAISE = 29;
  public static final int NONLOCAL = 25;
  public static final int SEMI = 69;
  public static final int GET = 56;
  public static final int LAMBDA = 24;
  public static final int PASS = 28;
  public static final int BLS = 47;
  public static final int INDENT = 84;
  public static final int F_DIV_EQ = 75;
  public static final int B_XOR_EQ = 79;
  public static final int BRS = 48;
  public static final int COMMA = 60;
  public static final int DEDENT = 85;
  public static final int RBRACE = 66;
  public static final int NOT_IN = 89;
  public static final int ELIF = 13;
  public static final int POW = 42;
  public static final int LT = 53;
  public static final int POW_EQ = 82;
  public static final int LBRACE = 65;
  public static final int LONG_INT = 91;
  public static final int MOD_EQ = 76;
  public static final int DEL = 12;
  public static final int YIELD = 34;
  public static final int FALSE = 83;
  public static final int NOT = 26;
  public static final int DEF = 11;
  public static final int NEQQ = 59;
  public static final int IMAG_NUMB = 93;
  public static final int ERROR = 2;
  public static final int FLOAT = 92;
  public static final int EQ = 36;
  public static final int MOD = 45;
  public static final int CLASS = 9;
  public static final int EXCEPT = 15;
  public static final int EXJOIN = 38;
  public static final int TRUE = 4;
  public static final int BRS_EQ = 80;
  public static final int PLUS = 39;
  public static final int IS_NOT = 90;
  public static final int EXEC = 88;
  public static final int B_OR = 50;
  public static final int LPAR = 61;
  public static final int WHILE = 32;
  public static final int B_AND_EQ = 77;
  public static final int NONE = 3;
  public static final int FOR = 17;
  public static final int DIV_EQ = 74;
  public static final int DIV = 43;
  public static final int RETURN = 30;
  public static final int MULT = 41;
  public static final int ELSE = 14;
  public static final int TRY = 31;
  public static final int BREAK = 8;
  public static final int DOT = 68;
  public static final int INT = 95;
  public static final int BLS_EQ = 81;
  public static final int RSB = 64;
  public static final int EQEQ = 57;
  public static final int EOF = 0;
  public static final int RPAR = 62;
  public static final int MINUS_EQ = 72;
  public static final int PRINT = 87;
  public static final int B_O_COMP = 52;
  public static final int IMPORT = 21;
  public static final int B_OR_EQ = 78;
  public static final int IS = 23;
  public static final int MINUS = 40;
  public static final int IN = 22;
  public static final int OR = 27;
  public static final int IDENT = 35;
  public static final int error = 1;
  public static final int FINALLY = 16;
  public static final int CONTINUE = 10;
  public static final int IF = 20;
  public static final int LSB = 63;
  public static final int COLON = 37;
  public static final int ASSERT = 7;
  public static final int MULT_EQ = 73;
  public static final int F_DIV = 44;
  public static final int GLOBAL = 19;
  public static final int STRING = 94;
  public static final int NEQ = 58;
  public static final int EXLINE = 67;
  public static final int AND = 5;
  public static final int LET = 55;
  public static final int WITH = 33;
  public static final int B_AND = 49;
}

